### ISSUE TITLE
Codegen does not support Object as potential parameter type

### ISSUE THREAD

**Issue by LyndonArmitage** [vert-x3/vertx-codegen#133]
As per comment left on the Java RabbitMQ client issue: https://github.com/vert-x3/vertx-rabbitmq-client/issues/38 by @thibaultleouay on an issue raised by @javiersigler .

The RabbitMQ Client does not support adding config options that are something other than Strings; this is especially problematic if you want to, for example, add a TTL to a queue. The [example RabbitMQ client](https://www.rabbitmq.com/ttl.html) makes use of a `Map<String,Object>` but the [vert.x client](http://vertx.io/docs/vertx-rabbitmq-client/java/#_declare_exchange_with_additional_config) uses a `Map<String, String>`. 

Unfortunately the underlying RabbitMQ library will throw an error message about wrong type if you feed it a `String.valueOf(number)` as it does not attempt to coerce the string back to a long.

```
2017-07-06 10:39:16.889 UTC [vert.x-eventloop-thread-5] ERROR c.s.h.service.RabbitService - Failed to declare queue: HEALTH_CHECKS
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:105) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:101) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:123) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:843) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:281) ~[amqp-client-3.6.5.jar:na]
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$queueDeclare$15(RabbitMQClientImpl.java:326) ~[vertx-rabbitmq-client-3.4.2.jar:na]
	at io.vertx.rabbitmq.impl.RabbitMQClientImpl.lambda$forChannel$22(RabbitMQClientImpl.java:424) ~[vertx-rabbitmq-client-3.4.2.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[vertx-core-3.4.2.jar:na]
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[vertx-core-3.4.2.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - invalid arg 'x-message-ttl' for queue 'HEALTH_CHECKS' in vhost '/': {unacceptable_type,longstr}, class-id=50, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:32) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:360) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:225) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:117) ~[amqp-client-3.6.5.jar:na]
	... 9 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - invalid arg 'x-message-ttl' for queue 'HEALTH_CHECKS' in vhost '/': {unacceptable_type,longstr}, class-id=50, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:483) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:320) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:143) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:90) ~[amqp-client-3.6.5.jar:na]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:559) ~[amqp-client-3.6.5.jar:na]
	... 1 common frames omitted
```

Would it be possible to alter the API to take a `JsonObject` or `Map<String, Object>`?

I apologise, I am not familiar with this codegen project so forgive me if I have not provided enough info, or if this has been been addressed in a different issue (I did a quick search but it is hard to know what keywords to use).

**Comment by vietj** [comment]
you can use `@GenIgnore(GenIgnore.PERMITTED_TYPE)`
