### ISSUE TITLE
Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found & the module-name conflict

### ISSUE THREAD

**Issue by UkonnRa** [vert-x3/vertx-codegen#179]
Hi! While compiling my Vertx project using `vertx-service-proxy`, I found I get an confusing error: `Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found`

Here is the pom.xml (Or you can get the whole project here: https://github.com/CasterKKK/CasterMovieVertx if you want):
```
<dependencies>
    ...
    <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-service-proxy</artifactId>
        <classifier>processor</classifier>
    </dependency>
    ...
</dependencies>

...
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler.version}</version>
        <configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <useIncrementalCompilation>false</useIncrementalCompilation>
            <encoding>${project.build.sourceEncoding}</encoding>
            <generatedSourcesDirectory>src/main/generated</generatedSourcesDirectory>
            <generatedTestSourcesDirectory>src/test/generated</generatedTestSourcesDirectory>
         </configuration>
           <executions>
                <execution>
                    <id>default-compile</id>
                        <configuration>
                            <annotationProcessors>
                                <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
                            </annotationProcessors>
                            <generatedSourcesDirectory>src/main/generated</generatedSourcesDirectory>
                            <compilerArgs>
                                <arg>-Acodegen.output=${project.basedir}/src/main</arg>
                            </compilerArgs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <configuration>
                            <annotationProcessors>
                                <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
                            </annotationProcessors>
                           <generatedTestSourcesDirectory>src/test/generated</generatedTestSourcesDirectory>
                       <compilerArgs>
                          <arg>-Acodegen.output=${project.basedir}/src/test</arg>
                    </compilerArgs>
                </configuration>
             </execution>
         </executions>
</plugin>
```

Show one of the Service:
```
@VertxGen
@ProxyGen
public interface UserService<T extends User> {

    @Fluent
    UserService register(T element, Handler<AsyncResult<T>> resultHandler) throws IOException;

    @Fluent
    UserService validate(UUID id, Handler<AsyncResult<T>> resultHandler) throws IOException;

    @Fluent
    UserService cancel(UUID id, Handler<AsyncResult<T>> resultHandler);

    @Fluent
    UserService update(UUID id, T element, Handler<AsyncResult<T>> resultHandler);

    @Fluent
    UserService getByJwt(String jwt, Handler<AsyncResult<T>> resultHandler);

    @Fluent
    UserService findById(UUID id, Handler<AsyncResult<T>> resultHandler);

    @Fluent
    UserService findByEmail(String email, Handler<AsyncResult<T>> resultHandler);

    @Fluent
    UserService findAllByState(State state, Handler<AsyncResult<List<T>>> resultHandler);

    @Fluent
    UserService findAllByCreateTimeBetween(Instant from, Instant to, Handler<AsyncResult<List<T>>> resultHandler);

    @Fluent
    UserService findAllByCancelledTimeBetween(Instant from, Instant to, Handler<AsyncResult<List<T>>> resultHandler);
}
```

And when using `mvn package -X -f pom.xml`, get an error:
```
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project user-module: Compilation failure
Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
Annotation processor 'io.vertx.codegen.CodeGenProcessor' not found

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1161)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :user-module
```

---

What's more, I found when I use
```
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-service-proxy</artifactId>
            <classifier>processor</classifier>
        </dependency>
```
and 
```
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-codegen</artifactId>
</dependency>
```
together, my `module-info.java` will get a `Module xxx reads package 'io.vertx.codegen' from both 'vertx.codegen' and 'vertx.codegen'` & `Ambiguous module reference: vertx.codege` error... What that mean?

**Comment by tsegismont** [comment]
It seems to me you shouldn't have the Maven compiler configuration. Just the processor dependency.

**Comment by CasterKKK** [comment]
@tsegismont can you say something more in detail?

**Comment by tsegismont** [comment]
I meant that to create service proxies you only need this in your POM:

```xml
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-codegen</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-service-proxy</artifactId>
      <classifier>processor</classifier>
    </dependency>
```

If you the `processor` dependency you must sitck to stock Maven `compiler` plugin configuration.

**Comment by CasterKKK** [comment]
Your solution is only avaliable before Java 9. In Java 9 or after, it will get a `Module xxx reads package 'io.vertx.codegen' from both 'vertx.codegen' and 'vertx.codegen'` as I mentioned before...

**Comment by tsegismont** [comment]
Ha sorry, I misunderstood the problem. I'm not sure this works on Java 9 if not in classpath mode. Can you confirm @vietj ?

**Comment by AngadRajput** [comment]
Hi all, to solve this just add the vertx-codegen and vertx-service-proxy dependencies in 
<annotationProcessorPaths>.

```xml
<configuration>
            <source>${java.version}</source>
            <target>${java.version}</target>
            <useIncrementalCompilation>false</useIncrementalCompilation>
            <encoding>${project.build.sourceEncoding}</encoding>
            <generatedSourcesDirectory>src/main/generated</generatedSourcesDirectory>
            <generatedTestSourcesDirectory>src/test/generated</generatedTestSourcesDirectory>
            <annotationProcessorPaths>
                        <dependency>
                            <groupId>io.vertx</groupId>
                            <artifactId>vertx-codegen</artifactId>
                            <version>${vertx.version}</version>
                        </dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-service-proxy</artifactId>
  <version>${vertx.version}</version>
</dependency>
                    </annotationProcessorPaths>
          
         </configuration>
```

**Comment by chefhoobajoob** [comment]
Can somebody translate this into Gradle 5.+? I can't get this error to go away on a project we have that is directly using `codegen`.

Gradle dependencies uses the new `annotationProcessor` configuration from gradle like so:
```
def vertxVersion = "3.6.3"
dependencies {
  // ...
    annotationProcessor "io.vertx:vertx-codegen:$vertxVersion"
}
```

...and has a compile task defined like so:
```
task generatePolyglotApis(type: JavaCompile) {
    group 'build'
    description 'Generates Vertx js and rxjava shims'
    source = sourceSets.main.java
    exclude("com/opentext/vertx/config/nimbus/**/*")
    classpath = configurations.annotationProcessor
    options.debugOptions.debugLevel = "source,lines,vars"
    options.compilerArgs = [
            "-proc:only",
            "-processor", "io.vertx.codegen.CodeGenProcessor",
            "-Acodegen.output=${projectDir}/src/main"
    ]
    destinationDir = file("${buildDir}/generated-sources/vertx")
}
```

**Comment by cvgaviao** [comment]
When using with maven and java9+ the right way to set is:
```
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <annotationProcessorPath>
                            <groupId>io.vertx</groupId>
                            <artifactId>vertx-codegen</artifactId>
                            <version>${vertx.version}</version>
                            <classifier>processor</classifier>
                        </annotationProcessorPath>
                        <annotationProcessorPath>
                            <groupId>io.vertx</groupId>
                            <artifactId>vertx-service-proxy</artifactId>
                            <version>${vertx.version}</version>
                            <classifier>processor</classifier>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

```
