### ISSUE TITLE
An exception occurred: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor

### ISSUE THREAD

**Issue by spydevil** [vert-x3/vertx-codegen#210]
When I was run compileKotlin task then I got an error. I'm confused for cause of error kapt or codegen

```
> Task :wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
w: C:\Users\sd\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.2.20\1ba23e74292b5af8980efde762fdd44fb61ddc2\kotlin-stdlib-jre7-1.2.20.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead
w: C:\Users\sd\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre8\1.2.20\f77d7863695e17041b50ebe5e2f87e5314a2c812\kotlin-stdlib-jre8-1.2.20.jar: kotlin-stdlib-jre8 is deprecated. Please use kotlin-stdlib-jdk8 instead
> Task :backend:kaptGenerateStubsKotlin
w: C:\Users\sd\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.2.20\1ba23e74292b5af8980efde762fdd44fb61ddc2\kotlin-stdlib-jre7-1.2.20.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead
w: C:\Users\sd\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre8\1.2.20\f77d7863695e17041b50ebe5e2f87e5314a2c812\kotlin-stdlib-jre8-1.2.20.jar: kotlin-stdlib-jre8 is deprecated. Please use kotlin-stdlib-jdk8 instead
[daemon-9668.out.log](https://github.com/vert-x3/vertx-codegen/files/2376284/daemon-9668.out.log)

[kapt] An exception occurred: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2243)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2252)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:748)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:891)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:279)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:117)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:968)
	at io.vertx.codegen.CodeGenProcessor.lambda$process$6(CodeGenProcessor.java:224)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.vertx.codegen.CodeGenProcessor.process(CodeGenProcessor.java:207)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:99)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:55)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:27)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:210)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:175)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:93)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:98)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:108)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:85)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:370)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:61)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:361)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:126)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:154)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:408)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$1$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:929)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:969)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:928)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 77 more
```

**build.gradle**

```
buildscript {
    ext.kotlin_version = '1.2.61'
    ext.vertx_version = '3.5.3'
    ext.arrow_version = '0.7.2'
    ext.mockk_version = '1.8.7'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0'
    }
}


apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'
apply plugin: 'org.junit.platform.gradle.plugin'

//noinspection GroovyUnusedAssignment
sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/exposed" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation 'org.jetbrains.exposed:exposed:0.10.4'

    implementation 'com.auth0:java-jwt:3.4.0'
    implementation 'com.rabbitmq:amqp-client:5.3.0'
    implementation 'com.microsoft.sqlserver:mssql-jdbc:7.0.0.jre8'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.9.6'

    implementation "io.vertx:vertx-web:$vertx_version"
    implementation "io.vertx:vertx-core:$vertx_version"
    implementation "io.vertx:vertx-lang-kotlin:$vertx_version"
    implementation "io.vertx:vertx-lang-kotlin-coroutines:$vertx_version"
    implementation "io.vertx:vertx-service-proxy:$vertx_version"
    implementation "io.vertx:vertx-codegen:$vertx_version"
    implementation "io.vertx:vertx-service-discovery:$vertx_version"
    implementation "io.vertx:vertx-hazelcast:$vertx_version"
    kapt "io.vertx:vertx-codegen:$vertx_version:processor"

    implementation "io.arrow-kt:arrow-core:$arrow_version"
    implementation "io.arrow-kt:arrow-syntax:$arrow_version"
    implementation "io.arrow-kt:arrow-typeclasses:$arrow_version"
    implementation "io.arrow-kt:arrow-data:$arrow_version"
    implementation "io.arrow-kt:arrow-instances-core:$arrow_version"
    implementation "io.arrow-kt:arrow-instances-data:$arrow_version"
    kapt "io.arrow-kt:arrow-annotations-processor:$arrow_version"

    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.1.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.1.1'
    testCompile "org.junit.platform:junit-platform-runner:1.3.0"
}

sourceSets {
    main {
        resources {
            srcDir "config"
        }
    }
}

junitPlatform {
    platformVersion '1.0.0'

    filters {
        engines {
            include 'junit-jupiter', 'junit-vintage'
        }
    }

    logManager 'org.apache.logging.log4j.jul.LogManager'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

kotlin {
    experimental {
        coroutines "enable"
    }
}
```
[daemon-9668.out.log](https://github.com/vert-x3/vertx-codegen/files/2376309/daemon-9668.out.log)

**Comment by vietj** [comment]
do you have the MVEL jar in your classpath ?

**Comment by spydevil** [comment]
```
@JsonIgnoreProperties(ignoreUnknown = true)
abstract class AbstractSocketMessage

@DataObject(generateConverter = true)
class SocketMessage() : AbstractSocketMessage() {

    lateinit var message: Message

    constructor(json: JsonObject) : this() {
        SocketMessageConverter.fromJson(json, this)
    }

    fun toJson(): JsonObject = JsonObject().also {
        SocketMessageConverter.toJson(this, it)
    }
	
}

@DataObject(generateConverter = true)
class SocketTopicMessage() : AbstractSocketMessage() {

    lateinit var message: TopicMessage

    constructor(json: JsonObject) : this() {
        SocketTopicMessageConverter.fromJson(json, this)
    }

    fun toJson(): JsonObject = JsonObject().also {
        SocketTopicMessageConverter.toJson(this, it)
    }
	
}


@DataObject(generateConverter = true)
class Message() {

    @JsonProperty("body")
    var body: String = ""

    constructor(json: JsonObject) : this() {
        MessageConverter.fromJson(json, this)
    }

    fun toJson(): JsonObject = JsonObject().also { MessageConverter.toJson(this, it) }

}

@DataObject(generateConverter = true)
class TopicMessage() {

    @JsonProperty("body")
    var body: String = ""
	
    @JsonProperty("topic")
    var topic: Int = -1

    constructor(json: JsonObject) : this() {
        TopicMessageConverter.fromJson(json, this)
    }

    fun toJson(): JsonObject = JsonObject().also { TopicMessageConverter.toJson(this, it) }

}
```

If I was delete `@DataObject(generateConverter = true)` from `SocketTopicMessage` class then my build work successfully. But if I don't delete it then I got an error `[kapt] An exception occurred: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor` 

Why I got this error on `SocketTopicMessage` class when I was add `@DataObject` annotation?

My **build.gradle** has mvel2 dependencies after your words. `implementation group: 'org.mvel', name: 'mvel2', version: '2.0'`

Very interesting 😄

**Comment by spydevil** [comment]
My `@DataObject` annotated class has this field;

```
    @JsonProperty("topic")
    var topic: TOPIC_ID = -1
```

When I was look the field type It's look like `typealias TOPIC_ID = Short` . When I was change `Short` type to `Int` the problem is gone.

**Comment by spydevil** [comment]
I've realized now;
I have **51** classes with `@DataObject(generateConverter = true)`
If I was compile I got a kapt error. But When I delete any of them It's work normally. No matter which one I delete.

**(Summarize) Number of @DataObject classes = 50+ kapt error, 50 and below successfully** 😕

**Comment by spydevil** [comment]
Any suggestion 😢 @vietj

**Comment by spydevil** [comment]
Any suggestion ? 😥 @vietj

**Comment by spydevil** [comment]
I can't add attachment on this thread: _https://groups.google.com/forum/?fromgroups#!topic/vertx/CRSn_Yv_hD8_  😨 😄

Vert.x 3.5.3 -> `java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor`
Vert.x 3.6.0-SNAPSHOT -> 
```
Could not generate model for Companion: type RequestService.Companion is not legal for use for a constant type in code generation
    public static final RequestService.Companion Companion = null;
```

[pseudo-project.zip](https://github.com/vert-x3/vertx-codegen/files/2393609/project.zip) @vietj

**Comment by vietj** [comment]
can you share it as a github project ?

**Comment by vietj** [comment]
```
MacBook-Pro-de-julien:vert.x julien$ jar -tvf /Users/julien/Downloads/project.zip 
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)
```

**Comment by spydevil** [comment]
https://github.com/spydevil/qwe 
_By the way that zip contains project folder It's not a jar._

**Comment by spydevil** [comment]
```
@DataObject(generateConverter = true)
class UpdateRequest() {
    var data: HashMap<String, Any>? = null

    constructor(json: JsonObject) : this() {
        UpdateRequestConverter.fromJson(json, this)
    }

    fun toJson() = JsonObject().also { UpdateRequestConverter.toJson(this, it) }
}
```
converter:
```
public class UpdateRequestConverter {

  public static void fromJson(Iterable<java.util.Map.Entry<String, Object>> json, UpdateRequest obj) {
    for (java.util.Map.Entry<String, Object> member : json) {
      switch (member.getKey()) {
      }
    }
  }

  public static void toJson(UpdateRequest obj, JsonObject json) {
    toJson(obj, json.getMap());
  }

  public static void toJson(UpdateRequest obj, java.util.Map<String, Object> json) {
  }
}
```

Everything good nice but, that codegen ruined me.... 😞

**Comment by spydevil** [comment]
Codegen doesn't generate `HashMap` why?
```
@DataObject(generateConverter = true)
class UpdateRequest() {
    var data: HashMap<String, Any>? = null

    constructor(json: JsonObject) : this() {
        UpdateRequestConverter.fromJson(json, this)
    }

    fun toJson() = JsonObject().also { UpdateRequestConverter.toJson(this, it) }
}
```
converter:
```
public class UpdateRequestConverter {

  public static void fromJson(Iterable<java.util.Map.Entry<String, Object>> json, UpdateRequest obj) {
    for (java.util.Map.Entry<String, Object> member : json) {
      switch (member.getKey()) {
      }
    }
  }

  public static void toJson(UpdateRequest obj, JsonObject json) {
    toJson(obj, json.getMap());
  }

  public static void toJson(UpdateRequest obj, java.util.Map<String, Object> json) {
  }
}
```

Everything good nice but, that codegen ruined me.... 😞

**Comment by vietj** [comment]
yes I understand, somebody will look at your case.

**Comment by EnilPajic** [comment]
Anything on this?

**Comment by vietj** [comment]
have you tried with 3.6.0.CR1 ?

**Comment by EnilPajic** [comment]
It seems that the error is gone. Thank you!

**Comment by vietj** [comment]
thanks
