### ISSUE TITLE
kaptKotlin failed when invoke fetchSourcePath in CodeGenProcessor

### ISSUE THREAD

**Issue by lightsing** [vert-x3/vertx-codegen#307]
### Version

4.0.0-milestone5

### Context

I encountered an exception which looks suspicious while gradle execute kaptKotlin.

A Gradle build scan is available [here](https://scans.gradle.com/s/2gnwxahww6koc).

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/workspace/moumoux/Outles/build/tmp/kapt3/classes/main/PathForCodeGenProcessor.class
at io.vertx.codegen.CodeGenProcessor.fetchSourcePath(CodeGenProcessor.java:152)
at io.vertx.codegen.CodeGenProcessor.loadJsonMappers(CodeGenProcessor.java:197)
at io.vertx.codegen.CodeGenProcessor.init(CodeGenProcessor.java:67)
```

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* [https://github.com/Project5E/outlets](https://github.com/Project5E/outlets)

### Steps to reproduce

1. clone it on Windows 10 with a Java8 env
2. ./gradlew.bat build

### Extra

**Build on Linux is successful**

Env | Name
-- | -- 
Operating system | Windows 10 10.0 
CPU cores | 6 cores 
Max Gradle workers | 6 workers 
Java runtime | Eclipse OpenJ9 OpenJDK Runtime Environment 1.8.0_265-b01 
Java VM | Eclipse OpenJ9 Eclipse OpenJ9 VM openj9-0.21.0 (mixed mode) 
Max JVM memory heap size | 536 MB 
Locale | Chinese (China) 
Default charset | UTF-8

**Comment by lightsing** [comment]
fixed in Beta.1
